version: "3.9"
services:
  beanstalk-flask:
    build:
      context: "."
      dockerfile: Dockerfile
    env_file:
      - env_vars.env
    ports:
      - "80:5000"
    volumes:
      - ./app:/app
    environment:
      FLASK_ENV: development
  

